### ISSUE TITLE
"No module named `mogptk.sm'"

### ISSUE THREAD

**Issue by jimmyrisk** [GAMES-UChile/mogptk#27]
Hi,

I'm following another example, which uses ``mogptk.CONV``.  I believe it's trying to reference something from an older version of package that has now moved.  

For reference, it's Example 6 (https://github.com/GAMES-UChile/mogptk/blob/master/examples/example_bramblemet.ipynb)

Here is the code and error with my data set, which is (basically) a copy paste of what is in the notebook.

```
modelCONV.init_parameters()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "c:\users\jrisk\dropbox\onedrive - cal poly pomona\research (new)\gp mortality python\src\mogptk\mogptk\models\conv.py", line 90, in init_parameters
    amplitudes, means, variances = self.dataset.get_sm_estimation(self.Q, method=sm_init, optimizer=sm_method, iters=sm_iters, params=sm_params, plot=sm_plot)
  File "c:\users\jrisk\dropbox\onedrive - cal poly pomona\research (new)\gp mortality python\src\mogptk\mogptk\dataset.py", line 620, in get_sm_estimation
    channel_amplitudes, channel_means, channel_variances = channel.get_sm_estimation(Q, method, optimizer, iters, params, plot)
  File "c:\users\jrisk\dropbox\onedrive - cal poly pomona\research (new)\gp mortality python\src\mogptk\mogptk\data.py", line 944, in get_sm_estimation
    from .sm import SM
  File "C:\Program Files\JetBrains\PyCharm 2020.3.4\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'mogptk.sm'
```

**Comment by tdewolff** [comment]
Thanks for the report, should be fixed now :-)
