### ISSUE TITLE
Issue LoadDataFrame with datetime64 and multi-inputs

### ISSUE THREAD

**Issue by Clej** [GAMES-UChile/mogptk#73]
I deal with spatio-temporal data and experience an issue at the data import when the latter have multiple inputs and one of the inputs is in a np.datetime64 format. I give a reproducing example:

```python
import mogptk
import pandas as pd
import numpy as np

print(f'numpy version: {np.__version__}')

df = pd.DataFrame(
    {'in1': [1, 0.5, 0.8],
     'in_timestep': [np.datetime64('2015-03-07'), np.datetime64('2015-04-07'), np.datetime64('2015-05-07')],
     'out1' : [1, 0, 1],
     'out2': [0, 1, 0]
     }
)

# no issue with
data = mogptk.LoadDataFrame(
    df=df,
    x_col=['in_timestep'],
    y_col=['out1', 'out2']
)

# issue with:
data = mogptk.LoadDataFrame(
    df=df,
    x_col=['in1', 'in_timestep'],
    y_col=['out1', 'out2']
)

print(f'#inputs={data.get_input_dims()}')
print(f'#outputs={data.get_output_dims()}')
```

which should outputs something like:

```
numpy version: 1.24.4
Traceback (most recent call last):
  File "/home/clej/miniconda3/envs/volcano/lib/python3.8/site-packages/mogptk/data.py", line 340, in _format_X
    X[i] = X[i].astype(np.datetime64)
ValueError: Could not convert object to NumPy datetime

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "volcano/exec/issue_mogptk_dataset.py", line 20, in <module>
    data = mogptk.LoadDataFrame(
  File "/home/clej/miniconda3/envs/volcano/lib/python3.8/site-packages/mogptk/dataset.py", line 118, in LoadDataFrame
    dataset.append(Data(
  File "/home/clej/miniconda3/envs/volcano/lib/python3.8/site-packages/mogptk/data.py", line 234, in __init__
    X, X_dtypes = self._format_X(X)
  File "/home/clej/miniconda3/envs/volcano/lib/python3.8/site-packages/mogptk/data.py", line 342, in _format_X
    raise ValueError("X data must have a number or datetime data type")
ValueError: X data must have a number or datetime data type
```

Had a look at the logs but cannot understand the reason of the failure as the time input is in numpy datetime64 format.

Have anyone experienced the same issue ?

**Comment by tdewolff** [comment]
Thanks for raising this issue, this is now fixed on master! Please confirm this works for you.

**Comment by Clej** [comment]
I confirm, now it works. Thanks for your very fast correction :)
